### ISSUE TITLE
Logging Questions

### ISSUE THREAD

**Issue by Olshansk** [fpereiro/backendlore#16]
This is the first "issue" I'm opening up to have a bit of a discussion, so I've got to say that I absolutely love the write up and appreciate that you took the time to share!

I'm trying to understand how your logging mechanism works. By specifying `logs = /tmp/MYAPP/logs`, do logs from a single node simply get written to the local file system of that node at that path? Would that mean there is no central aggregated (and preferably indexed) logging mechanism?

We used the [ELK Stack](https://www.elastic.co/what-is/elk-stack) at my previous company, which can be fully self hosted and is quite powerful when it comes to search and indexing. I'm curious what kind of technologies you've used along these lines?

**Comment by fpereiro** [comment]
Hi @Olshansk ! Glad you liked the write up!

Regarding logs, I've written a little bit about that on this section: https://github.com/fpereiro/backendlore#notification . Basically, all logs go to a logging service, instead of living on local files on the server - this requires a bit of extra code on the server, but in my opinion it is absolutely worth it to have a single funnel for all logging. The standard output of the process still goes somewhere, and I choose to put it in `/tmp/MYAPP/logs` since 1) that requires me to do no extra config with write permissions on the folder; and 2) local logs are deleted on server restart (which happen periodically in simple architectures like B and C - see https://github.com/fpereiro/backendlore#keeping-the-server-fresh), so there's no risk of the logs filling the disk - or requiring log rotation.

I recommend that sane persons use an established logging service (like Logstash, which is part of ELK). I don't have much experience using Logstash or any other standard logging services, so I cannot recommend any in particular.

For my own projects I use a barebones node.js service which receives logs from different servers and saves them in a single file, which still works quite well if the volume of logs is low. I plan to work, extend and eventually publish this service as part of ac;tools (https://github.com/altocodenl/actools). But so far it's all vaporware :).

I recommend that, no matter what solution you go with, you send your logs to a main funnel, one that ideally is 1) backed-up, 2) centralized (so you don't have to ssh here and there), and 3) searchable (so you're not opening multi-gb files in Vim as I have done too many times). And if you decide to keep your logs inside your servers, please use log rotation!

Hope that responds to your doubts. If there's anything in particular of the above you'd like me to add to the document, let me know.

Cheers!

**Comment by Olshansk** [comment]
Thanks for the quick reply and detailed explanation! Just to confirm, you have `stdout` logs go to a directory in `/tmp` AND have business logic that also makes a network request to log the same data to a centralized serve? If I'm understanding correctly, that makes complete sense and perhaps that wasn't too clear in the doc.

+100 regarding logs that are backed-up, centralized and searchable! I guess my question is why you built your own barebones node.js service as opposed to using ELK + Logstash or fluentd? I don't have a lot of personal experience setting these up myself, but was a user of something someone else had configured and it seemed to have worked well. Do you think it's worth adding them to the doc just as an FYI with the caveat that you haven't configured it yourself? I'm also completely open to setting this up myself and adding contributing to the doc with my experience.

I hope it's alright if I open other issues like this pertaining to discussions of other topics?

**Comment by fpereiro** [comment]
Hi @Olshansk !

- Just added a link to the Notification section from the relevant section (provisioning): https://github.com/fpereiro/backendlore/commit/82b4b7a8352b14c86e76dee680e07180a3038a6e
- In the notification section, I do recommend _saner people_ to use an established logging service. I don't do it because I'm a control freak and don't like adding external dependencies unless I absolutely love them or need them. Also, building your own tools is great fun and a way to learn a lot! But I digress :).
- I'd rather not recommend any particular logging services, since I'm not using any of them myself - if this changes in the future, I'll be sure to update the doc! In general, this document only discusses things that I've learned from personal experience and work with on a regular basis. For that reason, while I thank your suggestion, I'd rather not mention any particular tool in this regard. I trust that there should be enough info around to figure out good alternatives for logging services.

Feel free to open other issues regarding other topics!

**Comment by Olshansk** [comment]
> Also, building your own tools is great fun and a way to learn a lot

Haha, the real reason for `Not invented here` :)

Thanks a lot for the clarifications and @fpereiro!
