### ISSUE TITLE
Suggestion about deployment.

### ISSUE THREAD

**Issue by zhangyuheng** [fpereiro/backendlore#19]
Thanks for sharing your experience, this document is amazing👍.

Here is my suggestion:

Have you considered using docker to build and publish which performs consistent environment like vagrant you mentioned,
or even deploy the server into kubernetes cluster the cloud native way.
My experience is that you might not have to worry about local log, disk space, multi process cluster, master worker paradigm, re-fork/monitor worker processes.

**Comment by fpereiro** [comment]
Hi @zhangyuheng ! Glad you liked the document :)

Regarding Docker, I do speak a bit about it at the end of the Provisioning section (https://github.com/fpereiro/backendlore/#provisioning) and also a bit more in detail on this issue (https://github.com/fpereiro/backendlore/issues/11). My experience with Docker is limited though so it's definitely not an authoritative opinion.

Regarding kubernetes, I have barely any experience with it and so I decided not to talk about it, instead only focusing on what I know of and has worked for me. Any deployment system needs to deal with the things you mention (local log, disk space, clustering) but a good managed solution might pick sensible defaults (or provide sensible abstraction layers that solve most of the problem) and that's definitely a good thing! If it works for you, then that's great! I do admit I get overwhelmed with the little I've seen of k8s, because of the sheer complexity (in my view) of its APIs and its conceptual model. But I wouldn't want to discourage you or anyone from using it, lest of all if it works for you.

**Comment by fpereiro** [comment]
Feel free to reopen the issue if you have further questions!
