### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by Kryptos-FR** [fpereiro/backendlore#3]
From the [README](https://github.com/fpereiro/backendlore/blob/master/readme.md#license) file:

> This document is written by Federico Pereiro (fpereiro@gmail.com) and released into the public domain.

First of all, thanks. People publishing to public domain are rare.

Secondly, it is not very obvious at first since that license notice is only visible at the bottom of the file. Additionally, it might cause a bit of concern in places where public domain is not fully recognized or limited (e.g. where moral rights cannot be 100% waived).

So I propose to add a LICENSE file, that deals with those cases by explicitly stating those waivers.
I suggest to use either the [Unlicense](https://choosealicense.com/licenses/unlicense/) or the [CC0](https://choosealicense.com/licenses/cc0-1.0/)

If you think I am overreaching, feel free to close that issue :wink:

**Comment by fpereiro** [comment]
Hi Nicholas - first of all, thank you for your contribution!

You make very good points. I just added a clarification at the top of the readme.

As for public domain vs. using a very loose license, I feel strongly inclined towards the former. I love the idea of giving it all away through the concept of public domain, which has deep historical roots and sidesteps the contractual. If there's a single instance of someone not being able to use any of this (or any of my software, for that matter), I'll be glad to reconsider this stance.

Thanks!

**Comment by Kryptos-FR** [comment]
That's what the CC0 does: it is public domain with a fallback in case it doesn't apply for a particular case.

Maybe I am projecting a bit. In France, even with work in public domain, you can't automatically relinquish moral rights. So I know that I would need such license for work I create. Maybe you don't need it in your case.

In any case, thanks for the reply.

**Comment by prateekrastogi** [comment]
Does full praise misinformation of [Berne Convention](https://en.wikipedia.org/wiki/Berne_Convention) Obligatory.

**Comment by fpereiro** [comment]
Hi @Kryptos-FR ! I did a bit more of research about this. This section of a Wikipedia article (https://en.wikipedia.org/wiki/Public-domain-equivalent_license#Reception) actually comments on there not being a clear consensus in this matter; particularly, it highlights an interaction between two lawyers about this very issue:

- Position A (you still need a license to relinquish your rights): http://www.rosenlaw.com/lj16.htm
- Position B (you don't need a license to relinquish your rights): https://cr.yp.to/publicdomain.html

I read both of them carefully and found B more convincing. I must admit I'm biased towards B (the best case for this general outlook is made by Derek Sivers here: https://sivers.org/formalities). But the points made by Bernstein look solid on their own.

If anyone is truly impeded from using the information on this repo (or any of my publicly available code, including that of Altocode, my company), I will be glad to reconsider this stance, since I want everyone to be able to use my work.

I take this opportunity to _vous remercier_ for opening this issue - this helped me research and clarify my stance in this important matter.

**Comment by prateekrastogi** [comment]
thanks @fpereiro. Reminds me of Dinner's Philosophy for I/O duo programming.

**Comment by r-lyeh** [comment]
You can also go dual licensed: public domain and unlicense (including a link to unlicense.org is just fine)

**Comment by prateekrastogi** [comment]
@r-lyeh Like changing mobile keyboard layouts to colemak 🔢
