### ISSUE TITLE
How do you perform database migrations?

### ISSUE THREAD

**Issue by Aditya94A** [fpereiro/backendlore#6]
Would love to hear your thoughts on performing migrations. Do you have an automated setup/do it manually/ORM does it for you?

**Comment by fpereiro** [comment]
Hi @AdityaAnand1 ! Thanks for your excellent question. My experience migrating relational databases in production environments is non-existent, so I cannot be of help if you're working in such a context. I still added a section with info on how I perform changes to redis production databases, from which you might be able to salvage some useful info: https://github.com/fpereiro/backendlore#making-structural-changes-to-a-production-database

Feel free to reopen the issue if you have further questions!

**Comment by Olshansk** [comment]
The only point I can add to this is most ORM frameworks have DB migrations built-in. 

For example, if you're building a service in python using SQL alchemy, you might use [Alembic](https://alembic.sqlalchemy.org/en/latest/). If you're building a service in elixir, you might use [Ecto.Migration](https://hexdocs.pm/ecto_sql/Ecto.Migration.html). If, for example, you have 10 instances of your service running, you can launch a canary (1 our of the 10) containing the migration. The framework will detect that the database is out of date and perform it based on migration changes you specified.

The only important thing to note is that your migrations should be backwards compatible. If not, you could be in a situation where the DB has been migrated, but some of your instances are still using the old ORM while some instances are using the new ORM. If your changes MUST be backwards compatible, then you would have to bring down your service, perform the migration

**Comment by artjomsimon** [comment]
For me, it's important that the migration tool is separate from the language the app is written in, to prevent an implicit dependency there. We're using [Flyway](https://flywaydb.org) which served us well in the last years with all kind of scenarios. You write your migrations in SQL, and they're run in a transaction (if your database allows schema changes in a transaction (MySQL doesn't, that's why friends don't let friends use MySQL))

I'm skeptical about down (backwards) migrations and never do them. They're inherenty impossible if you're doing a destructive operation anyway. There are some techniques to prevent the discrepancy between code (e.g. an ORM) and your DB schema:

1. deploy additive change
2. deploy configuration to switch to new schema
3. deploy destructive change

The mental and cost ovehead of having back migrations isn't worth investing in *most* cases IMHO.

Instead of investing time into down migrations, it might be a good investment into separating the deployment from the activation of a feature. Like described above, you could roll out a new schema separately from the code using it, then, at a later time, activate the new code (timed, or by setting a feature flag in an admin dashboard, or whatever you like).

The Flyway website has more, and even more compelling takes against down migrations: https://flywaydb.org/documentation/command/undo#important-notes

**Comment by Olshansk** [comment]
That's interesting, I haven't heard of Flyway in the past.

Regarding down migrations, I'm also not a big fan. I was thinking more about backwards compatibility.

Consider the following two changes:

- Change1 (assume bar doesn't exist yet): `ALTER TABLE foo ADD bar INT;`

- Change2 (assume bar already exists as a VARCHAR): `ALTER TABLE foo ALTER COLUMN bar INT;`

Change2 can have so many problems during migration/deployment or if something needs to be rolled back, that I would personally prefer the following:

1. Create a column `bar2`
2. Deploy all instances and have them start populating data in `bar2`
3. Have another deployment or cron job that moves data from `bar` to `bar2` while validating that the the previous `VARCHARs` are proper `INTs`
4. Have another migration that drops `bar` and later renames renames `bar2` to `bar`

@artjomsimon Thoughts?
